### ISSUE TITLE
JavaBDD crashes when node array gets too big

### ISSUE THREAD

**Issue by dhendriks** [com-github-javabdd/com.github.javabdd#48]
JavaBdd can crash a follows:

```
java.lang.NegativeArraySizeException: -2130973901
	at com.github.javabdd.JFactory.doResize(JFactory.java:4547)
	at com.github.javabdd.JFactory.bdd_noderesize(JFactory.java:4533)
	at com.github.javabdd.JFactory.makenode(JFactory.java:4476)
	at com.github.javabdd.JFactory.bdd_makenode(JFactory.java:4414)
	at com.github.javabdd.JFactory.or_rec(JFactory.java:2254)
	at com.github.javabdd.JFactory.or_rec(JFactory.java:2253)
	at com.github.javabdd.JFactory.or_rec(JFactory.java:2252)
	at com.github.javabdd.JFactory.or_rec(JFactory.java:2252)
...
```

In `doResize`, the BDD node array is resized to a larger size, when needed. If it becomes too big, there is a signed integer overflow in computing the new size, and the size becomes negative, leading to a crash.

Ideally, we should increase to exactly `Integer.MAX_VALUE`, rather than overflowing. And the next time we should give some kind of out of memory error, with a proper message.

However, it seems we can't actually create arrays of size `Integer.MAX_VALUE`, but the exact size depends on the JVM. For instance, OpenJDK 15 on macOS allows at most `Integer.MAX_VALUE - 2`, see https://stackoverflow.com/a/3039805. Others suggest it may even be `- 8`, see https://stackoverflow.com/a/8381338. If a too large value is chosen, we get `OutOfMemoryError: Requested array size exceeds VM limit`, regardless of how much memory we have available.

**Comment by dhendriks** [comment]
You can find further information at:
* https://stackoverflow.com/questions/31382531/why-i-cant-create-an-array-with-large-size
* https://bugs.openjdk.org/browse/JDK-8029587 and https://bugs.openjdk.org/browse/JDK-8059914

Using `MAX_VALUE - 8` seems like a safe upper limit.
